FROM python:3.6

RUN groupadd -r student && \
    useradd -u 1000 -r -m -d /student -g student -s /bin/false student && \
    # Add required packages
    apt-get update && \
    apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      git

# Create environment
RUN pip install -U pip
